### ISSUE TITLE
Validations failed

### ISSUE THREAD

**Issue by scolandrea** [Glifery/EntityHiddenTypeBundle#3]
Hi,

Im not sure if im trying the right way but i cant validate if my hidden field is forced to be a empty or null. I wrote a constraint in my form_builder but didn't work.

Example:

```
$builder->add('brand', 'entity_hidden', array(
                    'class' => 'DomainBundle\Entity\Brand',
                    'constraints' => new Assert\NotBlank()
));
```

I did something wrong?

Thx

**Comment by Glifery** [comment]
Hi!
Sorry for the wait.

I've tried to repeat your case. I created an `entity_hidden` form type with a standard Symfony NotBlank constraint.

```
->add('entity', 'entity_hidden', array(
        'class' => 'VendorEntityHiddenTypeBundle:Entity',
        'property' => 'name',
        'data' => $entity,
        'constraints' => new \Symfony\Component\Validator\Constraints\NotBlank()
    ))
```

And when I tried to make it's value empty and submit the form, I got an error:

> This value should not be blank.

Sure, the form contains an error and $form->isValid() method returns `false`

Have you tried to use standard NotBlank constraint? Does the problem repeat with it? Or maybe you could share your constraint class for my check?

Thanks for report!
