### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by celsoandrade** [Glifery/EntityHiddenTypeBundle#7]
Hi,

Is this bundle ready for Symfony3?

Thank you,

**Comment by Glifery** [comment]
Hi @celsoandrade 
Unfortunately no, an actual `1.2.1` version of the bundle doesn't support Symfony3 yet.
We are working with that [here](https://github.com/Glifery/EntityHiddenTypeBundle/pull/6) but there are some unresolved problems. Please feel free to take a part in the discussion if you want.
Thanks!

**Comment by Glifery** [comment]
Symfony 3 support has been added in #11 PR
